sudo: required
dist: trusty
language: cpp
services:
  - docker

git:
  depth: 1

cache:
  directories:
    - $HOME/builder_ccache
    - $HOME/full_build
    - $HOME/proof-bin

env:
  global:
    - TARGET_NAME=`echo "$TRAVIS_REPO_SLUG" | sed -r 's|(.*/)?(.+)|\2|'`
    - PROOF_VERSION=0.18.7.6
    - PATH=$HOME/.local/bin:$PATH
    - secure: oRiXsVY5iZ/s51wVrgO4aq9Uiv/rR6JOwmvCbfYAZfKWZnZ4B8Muy/bDp8gERVPsax4+0kF+kpQZ8Xl99H0Y13LHWqL2q8u7/7yXk4CT2XnRhFNMjUTKM0iWQCjdvxW0xlV0j3mHx+2hswpYk7vsiH+tr4W83Y8aSYZ7NgAJBydMQeWhxPvVkrz1cXS1T1Bx0n0ynA/yMiOeZcu2JptOcySSk0GwHa/VBYDGjfqQdp5j2NcM29jSe4vxhTzkR+STIB6LB5SrbigxK2ZcbF394FS4HoXxxgITGYONo7fvtkoQIF+ahzhIFgNM/yZkLwKwCLD6WnoFSXTJPm4WbvWlhNLioD2ENk/ZFhYdOPG0fpiE61ch2xZ1WgGWVQ/LZABty1CPZcudnU6GohdkL3nmA+bkjAcepxbDO5rJkX9jpSkn9n7QE0ZM0brRKTIjBdvi8AgFDNLSDfwR8sPdT3aAaLBl7ZjuNgxidrKtMJMDKzNI3+cp2mqq8n01q5OZI8WrgJuYHoux0K0qg4SzSsB2XgVp+zbSKJ5xExZqs4mYZa5IBYZfAD3zv+nykmORo18IHpdSNW2SJLeRGYxYSci3udvjCQirClVhQxkrO6Mtx+U4cL5IQHY3UG+v8TpeRLYaK6TtyvUTTd3SbSErGrwNqGyAATIVC+tbaFilcZB2tgs=
    - secure: Q/vZzd1hgCdubBmuCCkXTOBz5AR0o3VAWNGPrL92CEupxcY+4uD4cgmnxB15kSjo5fHAwdB8PJ7DjdcX7msUCxNuzymVBtUBajYCBwQS9p+8hlaoG94XklW99ECDSocKChaY41Kx6mUWJnzFLgACjnEK9lG3gATrhMgErv2EPKbwfJgJ1Ba/aW3z1CY10ru+n83MI2d+OGX6mayOfV8SeIc3eSdmw0Fzs7Bw9uLxbQLm+j7d4UaWH9S9+isI9RiVNHGckg6uUNVCdRgT3DAD4jfXBaQTf87f8Q98y7JiJKdJ8LC45YaKH3bBxSU+Beq0lLYc3j7VeKrkCENYLVO78g9/zVhpnMedWjliNXua25ik+0Ielz2H3pkp1gcnyxtUj1YKUwITCvn5jmvvLtmsX+r7JEiLiXasGpWwxCeCPhCRHrsj2vSUZ+h9u32C6oy/0nvQwaSOW/Xe0JM/y2f8vMypdqq00bPUKt5RH8U3m8yF+UPwK+vzy+q6ZGXCLksC1jF4H6izFqvMFwT6GjD/mCCE7l2Um7+nPLYT9Z8Dq6BOOuILWnt3dbX3lirG2eJ1D+ZPRE+9hs7ccW2YXtylO/OmmVcjmxs4wX73a7kzvj42TGQxjMWP9NVOk3SNmK9zxcT6nlY8fsJIxkuUL0B/OJE1SIYLQ4hyt7JTlxRclak=

before_install: export -f travis_fold && export -f travis_time_start && export -f travis_time_finish && export -f travis_nanoseconds

jobs:
  include:
    - &pre-compile
      stage: Pre compilation
      name: Proof installation (non-release)
      if: type != pull_request AND tag IS blank AND branch != master
      before_script: pip install --user awscli
      script:
        - cd $HOME
        - aws s3 cp s3://proof.travis.builds/$TRAVIS_BRANCH/proof-bin-debian9.tar.gz proof-bin.tar.gz ||
          aws s3 cp s3://proof.travis.builds/develop/proof-bin-debian9.tar.gz proof-bin.tar.gz || travis_terminate 1
        - rm -rf proof-bin && tar -xzf proof-bin.tar.gz
    - <<: *pre-compile
      name: Proof installation (release)
      if: type != pull_request AND (tag IS present OR branch = master)
      before_script: pip install --user awscli
      script:
        - cd $HOME
        - aws s3 cp s3://proof.travis.builds/__releases/proof/$PROOF_VERSION/proof-bin-debian9.tar.gz proof-bin.tar.gz || travis_terminate 1
        - rm -rf proof-bin && tar -xzf proof-bin.tar.gz
    - &compile
      stage: compilation and static checks
      name: Compilation (with ccache)
      before_script: export EXTRA_DEPS='libusb-1.0-0-dev'
      script: $HOME/proof-bin/dev-tools/travis/apps/compile/linux_compile.sh
    - <<: *compile
      name: Code style check with clang-format
      script: $HOME/proof-bin/dev-tools/travis/apps/compile/clang-format_check.sh
    - <<: *compile
      name: Static code analysis with clazy
      script: $HOME/proof-bin/dev-tools/travis/apps/compile/clazy_check.sh
    - &post-compile
      stage: Post compilation
      name: Debian package upload to S3 (non-release)
      if: type != pull_request AND tag IS blank AND branch != master
      script: $HOME/proof-bin/dev-tools/travis/apps/post-compile/deb_upload.sh
    - <<: *post-compile
      name: Debian package upload to S3 (release)
      if: type != pull_request AND tag IS present
      script: $HOME/proof-bin/dev-tools/travis/apps/post-compile/deb_upload.sh release
